# dbt Cloud Starter Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DBT_API_KEY:             $DBT_CLOUD_API_KEY
  DBT_URL:                 https://cloud.getdbt.com # no trailing backslash. Change this for single tenant deployments to your actual base url
  DBT_JOB_CAUSE:           'Azure Pipelines Pull Request Job' # provide a descriptive job cause here for easy debugging down the road
  DBT_ACCOUNT_ID:          16173
  DBT_PROJECT_ID:          85642
  DBT_PR_JOB_ID:           71253
  DBT_JOB_SCHEMA_OVERRIDE: PR_AZURE_PIPELINES_$(System.PullRequest.PullRequestId)
  DBT_JOB_BRANCH:          $(System.PullRequest.SourceBranch)

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'

- script: |
    pip install requests

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './scripts/run_and_monitor_dbt_cloud_job.py'