name: tpch
version: 1.0.0
config-version: 2
profile: tpch
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: target
clean-targets:
  - target
  - dbt_modules
# on-run-start:
  # - alter warehouse transforming set warehouse_size=small;
  # - '{{create_udfs()}}'
# on-run-end:
  # - alter warehouse transforming set warehouse_size=xsmall;
  # - '{{ grant_all_on_schemas(schemas, ''transformer'') }}'
vars:
  dbt_metrics_calendar_model: ref('metric_calendar_custom')
  load_type: I
  start_date: '1999-01-01'
  test: 'false'
  fct_order_items: mock_source__fct_order_items
  dbt_artifacts:
    dbt_artifacts_schema: dbt_artifacts_sung
    dbt_artifacts_table: artifacts
  data_diff:
    prod_database: DEV
    prod_schema: prod_sung
models:
  dbt_artifacts:
    +schema: dbt_artifacts_sung
    staging:
      +schema: dbt_artifacts_sung
  tpch:
    staging:
      # database: '{{ env_var("DBT_DYNAMIC_DATABASE","sung_demo") }}'
      +materialized: view
    marts:
      core:
        +tags: owner:sung
        materialized: table
  snowflake_spend:
    enabled: false
seeds:
  tpch:
    snowflake_contract_rates:
      +column_types:
        effective_date: DATE
        rate: NUMBER
