tpch:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: zna84829

      # User/password auth
      user: sung_c
      password: "{{ env_var('SFPASS') }}"

      database: ANALYTICS
      warehouse: TRANSFORMING
      schema: dbt_sung
      threads: 8
      client_session_keep_alive: True
      query_tag: