tpch:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: bya42734

      # User/password auth
      user: sung
      password: "{{ env_var('SFPASS') }}"

      database: ANALYTICS
      warehouse: TRANSFORMING
      schema: dbt_sung
      threads: 24
      client_session_keep_alive: True
      query_tag: